// the-samples/reactions-svelte/src/lib/Tally.svelte
<script lang="ts">
  import type { Count } from "tally-tool";
  import { TallyTool } from "tally-tool";

  export let name: string;
  export let image: string;

  const tally = new TallyTool(import.meta.env.VITE_APP_URL)
    .namespace("reactions")
    .tally(name);

  let count = "";
  let completed = false;

  const update = (c: Count) => {
    count = c.tally.count.toString();
    completed = c.completed;
  };

  const getCount = () => tally.get().then(update);
  const incCount = () => tally.increment().then(update);
  const decCount = () => tally.decrement().then(update);

  getCount();
</script>

  <div class="card">
    <img src={image} alt={name} />

    <h2>{count}</h2>

    <div class="btns">
      <button disabled={completed} on:click={incCount}> + </button>
      <button disabled={completed} on:click={decCount}> - </button>
    </div>
  </div>

// the-samples/reactions-react/src/Tally.tsx
import { TallyTool } from "tally-tool";
import { useQuery, useMutation, useQueryClient } from "react-query";

const tally = new TallyTool(import.meta.env.VITE_APP_URL);
const reactions = tally.namespace("reactions");

type TallyProps = {
  name: string;
  image: string;
};

function Tally({ name, image }: TallyProps) {
  const tally = reactions.tally(name);

  const queryClient = useQueryClient();
  const { data } = useQuery(["reactions", name], () => tally.get());

  const inc = useMutation(() => tally.increment(), {
    onSuccess: (data) => {
      queryClient.setQueryData(["reactions", name], data);
    },
  });

  const dec = useMutation(() => tally.decrement(), {
    onSuccess: (data) => {
      queryClient.setQueryData(["reactions", name], data);
    },
  });

  return (
    <div className="card">
      <img src={image} />
      <h2>{data?.tally.count}</h2>
      <div className="btns">
        <button disabled={data?.completed} onClick={() => inc.mutate()}> + </button>
        <button disabled={data?.completed} onClick={() => dec.mutate()}> - </button>
      </div>
    </div>
  );
}

export default Tally;
